import { Product } from "./types";

export const CATEGORIES = ["All", "Electronics", "Clothing", "Home & Living", "Sports", "Beauty"];

export const products: Product[] = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    category: "Electronics",
    price: 79.99,
    originalPrice: 129.99,
    rating: 4.8,
    reviewCount: 2341,
    image: "https://m.media-amazon.com/images/I/51f7KKP25PL._AC_UF894,1000_QL80_.jpg",
    badge: "sale",
    description: "Premium sound with active noise cancellation and 30-hour battery life.",
    inStock: true,
  },
  {
    id: 2,
    name: "Minimalist Leather Watch",
    category: "Clothing",
    price: 149.00,
    rating: 4.7,
    reviewCount: 876,
    image: "https://watchwithsun.com/wp-content/uploads/2024/11/watch406-04.jpg",
    badge: "bestseller",
    description: "Slim profile with genuine leather strap and sapphire crystal glass.",
    inStock: true,
  },
  {
    id: 3,
    name: "Smart Fitness Tracker Band",
    category: "Sports",
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.5,
    reviewCount: 1543,
    image: "https://m.media-amazon.com/images/I/71KwGt+7qSL._AC_UF894,1000_QL80_.jpg",
    badge: "sale",
    description: "Track steps, heart rate, sleep, and more with a 7-day battery.",
    inStock: true,
  },
  {
    id: 4,
    name: "Ceramic Pour-Over Coffee Set",
    category: "Home & Living",
    price: 64.00,
    rating: 4.9,
    reviewCount: 412,
    image: "https://m.media-amazon.com/images/I/7159+ELcEOL._AC_UF894,1000_QL80_.jpg",
    badge: "new",
    description: "Handcrafted ceramic dripper with matching mug and bamboo stand.",
    inStock: true,
  },
  {
    id: 5,
    name: "Ultra-Slim Laptop Stand",
    category: "Electronics",
    price: 39.99,
    originalPrice: 54.99,
    rating: 4.6,
    reviewCount: 987,
    image: "https://m.media-amazon.com/images/I/51MSM1V3CoS.jpg",
    badge: "hot",
    description: "Adjustable aluminum stand compatible with all laptops up to 17 inches.",
    inStock: true,
  },
  {
    id: 6,
    name: "Organic Cotton Oversized Hoodie",
    category: "Clothing",
    price: 58.00,
    rating: 4.7,
    reviewCount: 2109,
    image: "https://i.etsystatic.com/10302990/r/il/d243ab/4340458412/il_fullxfull.4340458412_dxms.jpg",
    badge: "bestseller",
    description: "100% organic cotton, pre-washed for extra softness. Available in 8 colors.",
    inStock: true,
  },
  {
    id: 7,
    name: "Portable Bluetooth Speaker",
    category: "Electronics",
    price: 59.99,
    originalPrice: 89.99,
    rating: 4.4,
    reviewCount: 3201,
    image: "https://cdn.thewirecutter.com/wp-content/media/2024/11/portablebluetoothspeakers-2048px-9130.jpg?width=2048&quality=60&crop=2048:1365&auto=webp",
    badge: "sale",
    description: "360° surround sound, waterproof IPX7, and 12-hour playtime.",
    inStock: true,
  },
  {
    id: 8,
    name: "Yoga Mat with Alignment Lines",
    category: "Sports",
    price: 45.00,
    rating: 4.8,
    reviewCount: 654,
    image: "https://cdn.shopify.com/s/files/1/0868/4453/9204/files/TPE_Alignment_Mat_Image_02v2_480x480.jpg?v=1737458389",
    badge: "new",
    description: "Non-slip 6mm thick mat with printed alignment guides for perfect form.",
    inStock: true,
  },
  {
    id: 9,
    name: "Vitamin C Brightening Serum",
    category: "Beauty",
    price: 34.99,
    originalPrice: 49.99,
    rating: 4.6,
    reviewCount: 1876,
    image: "https://m.media-amazon.com/images/I/71cFGPWHYoL._AC_UF1000,1000_QL80_.jpg",
    badge: "sale",
    description: "20% Vitamin C with hyaluronic acid for radiant, even-toned skin.",
    inStock: true,
  },
  {
    id: 10,
    name: "Linen Throw Pillow Set",
    category: "Home & Living",
    price: 42.00,
    rating: 4.5,
    reviewCount: 321,
    image: "https://m.media-amazon.com/images/I/81g-wfGYICL.jpg",
    description: "Set of 2 natural linen pillows with removable covers. 18×18 inches.",
    inStock: true,
  },
  {
    id: 11,
    name: "Mechanical Gaming Keyboard",
    category: "Electronics",
    price: 119.99,
    originalPrice: 159.99,
    rating: 4.7,
    reviewCount: 4532,
    image: "https://m.media-amazon.com/images/I/71VIc-MHaNL._AC_UF894,1000_QL80_.jpg",
    badge: "hot",
    description: "TKL layout with Cherry MX switches and per-key RGB backlighting.",
    inStock: true,
  },
  {
    id: 12,
    name: "Stainless Steel Water Bottle",
    category: "Sports",
    price: 28.00,
    rating: 4.9,
    reviewCount: 5678,
    image: "https://m.media-amazon.com/images/I/6179bFEXjiL.jpg",
    badge: "bestseller",
    description: "Double-wall insulated, keeps drinks cold 24h or hot 12h. 32oz.",
    inStock: true,
  },
  {
    id: 13,
    name: "Retinol Night Repair Cream",
    category: "Beauty",
    price: 44.99,
    rating: 4.5,
    reviewCount: 923,
    image: "https://i5.walmartimages.com/seo/No7-Pure-Retinol-Night-Repair-Cream-with-Collagen-Peptides-and-Bisabolol-All-Skin-Types-1-69-oz_7cac67a8-716b-4c60-aaa5-ab8ce884fbd3.872211a04cbbec8f8ff8c038934dd907.png",
    badge: "new",
    description: "0.3% encapsulated retinol with peptides for overnight skin renewal.",
    inStock: true,
  },
  {
    id: 14,
    name: "Bamboo Desk Organizer Set",
    category: "Home & Living",
    price: 36.00,
    originalPrice: 48.00,
    rating: 4.6,
    reviewCount: 445,
    image: "https://m.media-amazon.com/images/I/81KVrn5Sv1L.jpg",
    badge: "sale",
    description: "5-piece sustainable bamboo set to keep your workspace tidy and stylish.",
    inStock: true,
  },
  {
    id: 15,
    name: "Running Shoes Lightweight",
    category: "Sports",
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.7,
    reviewCount: 2876,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEXwjPNoxeLtrXxfjdATn2tB4NIGVs5EWViQ&s",
    badge: "sale",
    description: "Ultra-lightweight mesh upper with responsive foam midsole for daily runs.",
    inStock: true,
  },
  {
    id: 16,
    name: "Slim Fit Chino Trousers",
    category: "Clothing",
    price: 52.00,
    rating: 4.4,
    reviewCount: 1234,
    image: "https://m.media-amazon.com/images/I/61ELTn+o-SL._AC_UY1000_.jpg",
    description: "Stretch cotton blend for all-day comfort. Available in 6 colors.",
    inStock: true,
  },
];
